[package]
name = "example-tera-templating"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { workspace = true, features = ["tera"] }
tokio = { workspace = true, features = ["full"] }
once_cell = "1.17.0"
